# Generated by Django 3.2.12 on 2023-02-01 23:53

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
                ('checked', models.BooleanField(blank=True, default=False, null=True, verbose_name='Checked')),
            ],
        ),
        migrations.CreateModel(
            name='ContentKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=100, null=True, verbose_name='keyword')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='category')),
            ],
        ),
        migrations.CreateModel(
            name='DomainExtract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, default=False, max_length=300, null=True, verbose_name='link')),
            ],
        ),
        migrations.CreateModel(
            name='EmailExtract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, default=False, max_length=100000, null=True, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='ImageToText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/', verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='NumberExtract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(blank=True, default=False, null=True, verbose_name='phone')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_str', models.CharField(blank=True, max_length=100, null=True, verbose_name='ref_str')),
            ],
        ),
        migrations.CreateModel(
            name='Wrodcounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default=False, max_length=100000, null=True, verbose_name='text')),
            ],
        ),
        migrations.AddIndex(
            model_name='wrodcounter',
            index=models.Index(fields=['text'], name='tools_wrodc_text_929c17_idx'),
        ),
        migrations.AddField(
            model_name='reference',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference', to='tools.content', verbose_name='content'),
        ),
        migrations.AddIndex(
            model_name='numberextract',
            index=models.Index(fields=['phone'], name='tools_numbe_phone_ac845c_idx'),
        ),
        migrations.AddIndex(
            model_name='imagetotext',
            index=models.Index(fields=['image'], name='tools_image_image_e1bbfa_idx'),
        ),
        migrations.AddIndex(
            model_name='emailextract',
            index=models.Index(fields=['email'], name='tools_email_email_f4a460_idx'),
        ),
        migrations.AddIndex(
            model_name='domainextract',
            index=models.Index(fields=['link'], name='tools_domai_link_4bf728_idx'),
        ),
        migrations.AddIndex(
            model_name='contentkeyword',
            index=models.Index(fields=['keyword'], name='tools_conte_keyword_ee2b5b_idx'),
        ),
        migrations.AddField(
            model_name='content',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='tools.contentkeyword', verbose_name='keyword'),
        ),
        migrations.AddIndex(
            model_name='reference',
            index=models.Index(fields=['ref_str', 'content'], name='tools_refer_ref_str_2af722_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['content'], name='tools_conte_content_bd5486_idx'),
        ),
    ]
