# Generated by Django 3.1.5 on 2022-05-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailExtract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=300, null=True, verbose_name='email')),
            ],
        ),
        migrations.AddIndex(
            model_name='emailextract',
            index=models.Index(fields=['email'], name='tools_email_email_f4a460_idx'),
        ),
    ]
