# Generated by Django 3.1.5 on 2022-06-29 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default=False, max_length=100, null=True, verbose_name='category')),
                ('keyword', models.CharField(blank=True, default=False, max_length=100, null=True, verbose_name='keyword')),
            ],
        ),
        migrations.CreateModel(
            name='AutomaticArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(blank=True, default=False, max_length=300, null=True, verbose_name='article')),
            ],
        ),
        migrations.CreateModel(
            name='DomainExtract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, default=False, max_length=300, null=True, verbose_name='link')),
            ],
        ),
        migrations.CreateModel(
            name='EmailExtract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, default=False, max_length=100000, null=True, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='ImageToText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/', verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='NumberExtract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(blank=True, default=False, null=True, verbose_name='phone')),
            ],
        ),
        migrations.AddIndex(
            model_name='numberextract',
            index=models.Index(fields=['phone'], name='tools_numbe_phone_ac845c_idx'),
        ),
        migrations.AddIndex(
            model_name='imagetotext',
            index=models.Index(fields=['image'], name='tools_image_image_e1bbfa_idx'),
        ),
        migrations.AddIndex(
            model_name='emailextract',
            index=models.Index(fields=['email'], name='tools_email_email_f4a460_idx'),
        ),
        migrations.AddIndex(
            model_name='domainextract',
            index=models.Index(fields=['link'], name='tools_domai_link_4bf728_idx'),
        ),
        migrations.AddField(
            model_name='automaticarticle',
            name='category',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='tools.articlecategory', verbose_name='category'),
        ),
        migrations.AddIndex(
            model_name='articlecategory',
            index=models.Index(fields=['category'], name='tools_artic_categor_8f758a_idx'),
        ),
        migrations.AddIndex(
            model_name='automaticarticle',
            index=models.Index(fields=['article'], name='tools_autom_article_82381d_idx'),
        ),
    ]
