# Generated by Django 3.1.5 on 2022-08-07 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=300, null=True, verbose_name='article')),
            ],
        ),
        migrations.CreateModel(
            name='ContentKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=100, null=True, verbose_name='keyword')),
            ],
        ),
        migrations.RemoveField(
            model_name='automaticarticle',
            name='category',
        ),
        migrations.DeleteModel(
            name='ArticleCategory',
        ),
        migrations.DeleteModel(
            name='AutomaticArticle',
        ),
        migrations.AddIndex(
            model_name='contentkeyword',
            index=models.Index(fields=['keyword'], name='tools_conte_keyword_ee2b5b_idx'),
        ),
        migrations.AddField(
            model_name='content',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='tools.contentkeyword', verbose_name='keyword'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['content'], name='tools_conte_content_bd5486_idx'),
        ),
    ]
