# Generated by Django 3.1.5 on 2022-08-20 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_auto_20220808_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_str', models.CharField(blank=True, max_length=100, null=True, verbose_name='ref_str')),
                ('checked', models.BooleanField(blank=True, default=False, null=True, verbose_name='Checked')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference', to='tools.contentkeyword', verbose_name='keyword')),
            ],
        ),
        migrations.AddIndex(
            model_name='reference',
            index=models.Index(fields=['ref_str', 'keyword'], name='tools_refer_ref_str_33ee4d_idx'),
        ),
    ]
