# Generated by Django 3.1.5 on 2022-08-22 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_contentkeyword_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference', to='tools.content', verbose_name='keyword'),
        ),
    ]
