# Generated by Django 3.1.5 on 2022-08-22 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_auto_20220822_0755'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reference',
            name='tools_refer_ref_str_33ee4d_idx',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='checked',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='keyword',
        ),
        migrations.AddField(
            model_name='content',
            name='checked',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Checked'),
        ),
        migrations.AddField(
            model_name='reference',
            name='content',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reference', to='tools.content', verbose_name='content'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='reference',
            index=models.Index(fields=['ref_str', 'content'], name='tools_refer_ref_str_2af722_idx'),
        ),
    ]
